name: ci

on:
  push:

env:
  DOCKER_REGISTRY: docker.chameleoncloud.org
  KOLLA_BRANCH: chameleoncloud/train
  OPENSTACK_BASE_RELEASE: train
jobs:
  buildx:
    environment: Chameleon CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        base_os: [debian, ubuntu, centos]
        include:
          - arch: x86_64
            platform: linux/amd64
          - arch: aarch64
            platform: linux/arm64
          - base_os: debian
            os_tag: 10
          - base_os: ubuntu
            os_tag: 18.04
          - base_os: centos
            os_tag: 8
          - extra_os: centos7
            base_os: centos
            os_tag: 7
            arch: x86_64
            platform: linux/amd64
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: |
          echo "KOLLA_NAMESPACE=kolla-dev" >> $GITHUB_ENV
          echo "KOLLA_PUSH=yes" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "KOLLA_NAMESPACE=kolla" >> $GITHUB_ENV
          echo "KOLLA_PUSH=yes" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Cache python deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Registry
        uses: docker/login-action@v1
        if: env.KOLLA_PUSH == 'yes'
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.CC_REGISTRY_USERNAME }}
          password: ${{ secrets.CC_REGISTRY_PASSWORD }}
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: delete env files
        run: find . -type f -name "*.env" -delete
      - name: Run Kolla Build
        env:
          KOLLA_USE_CACHE: no
          KOLLA_INSTALL_TYPE: source
          KOLLA_BUILD_PROFILE: base
          KOLLA_BASE: ${{ matrix.base_os }}
          KOLLA_BASE_TAG: ${{ matrix.os_tag }}
          KOLLA_BASE_ARCH: ${{ matrix.arch }}
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}
          DOCKER_TAG: ${{ env.OPENSTACK_BASE_RELEASE }}-${{ matrix.base_os }}${{ matrix.os_tag}}-${{ matrix.arch }}
        run: make build
      - name: List Build Images
        run: docker image ls